"""empty message

Revision ID: 84fa61cdff2b
Revises: 2faf981d8e22
Create Date: 2022-05-15 12:48:32.238991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84fa61cdff2b'
down_revision = '2faf981d8e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('profile_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'profile_path')
    # ### end Alembic commands ###
